### ISSUE TITLE
Add support for '--all' option in 'jool stats display' command.

### ISSUE THREAD

**Issue by basovnik** [cooperlees/jool-exporter#1]
Could you please add support for `-all` option in `jool stats display` command?
https://github.com/cooperlees/jool-exporter/blob/main/jool_exporter.py#L64
This option adds a lot of other useful metrics.
```
$ jool stats display --all
JSTAT_RECEIVED4: 4527
JSTAT_SUCCESS: 0
JSTAT_BIB_ENTRIES: 0
JSTAT_SESSIONS: 0
JSTAT_ENOMEM: 0
JSTAT_XLATOR_DISABLED: 0
JSTAT_POOL6_UNSET: 0
JSTAT_SKB_SHARED: 0
JSTAT_L3HDR_OFFSET: 0
JSTAT_SKB_TRUNCATED: 0
JSTAT_FRAGMENTED_PING: 0
JSTAT_HDR6: 0
JSTAT_HDR4: 0
JSTAT_UNKNOWN_L4_PROTO: 0
JSTAT_UNKNOWN_ICMP6_TYPE: 0
JSTAT_UNKNOWN_ICMP4_TYPE: 0
JSTAT_DOUBLE_ICMP6_ERROR: 0
JSTAT_DOUBLE_ICMP4_ERROR: 0
...
```

**Comment by cooperlees** [comment]
Sure, sounds good to me. I missed this option. I'm also happy to default to `--all`. I will eventually get to this but will accept a PR. The PR could also make this a param to the web call for extra points if people prefer that.
